spring.application.name=atm-backend

# ===== STEP 0 =====

# ===== DATABASE CONFIGURATION =====
spring.datasource.url=jdbc:mysql://localhost:3306/atm_bank
spring.datasource.username=root
spring.datasource.password=root

# setting controls whether Hibernate tries to create or modify your database tables based on your Java Entity classes.
spring.jpa.hibernate.ddl-auto=validate

# prints every SQL query Hibernate generates to your console
spring.jpa.show-sql=true 

server.port=8081
# ==================================